// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Greeter is an autogenerated mock type for the Greeter type
type Greeter struct {
	mock.Mock
}

// Greet provides a mock function with given fields: msg
func (_m *Greeter) Greet(msg string) string {
	ret := _m.Called(msg)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewGreeter interface {
	mock.TestingT
	Cleanup(func())
}

// NewGreeter creates a new instance of Greeter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGreeter(t mockConstructorTestingTNewGreeter) *Greeter {
	mock := &Greeter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
