name: Upgrade Dependencies
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 1 * *' # At 00:00 on day-of-month 1.
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.18']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Upgrade dependencies
        run: go get -u -t ./...
      - name: Run test
        run: go test ./...
      - name: Commit changes
        run: git status && git add go.mod go.sum && git commit -m "Upgrade changes"
      
